spring:
  datasource:
    username: root
    password: "0212"
    url: jdbc:mysql:///auctiononlinesys?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
